# Generated by Django 4.0.4 on 2022-06-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_service_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
