# Generated by Django 4.0.4 on 2022-06-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(default=0, max_length=256, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(max_length=256, verbose_name='Время оказания'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Нименование услуги'),
        ),
    ]
