# Generated by Django 4.0.4 on 2022-06-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_salon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='salon',
        ),
    ]
